## Core Functions
- Report the range of times for each event for the given data set (done)
- Report the median time for each for the selected data set (done)
- Report fastest for each event along with that person and the rest of their time (EX "Christina Hepper has the fastest Swim at _____ and had the following other times...., Jamie Fend had the fastest T1 at _____ and had teh following other times...." (done, but need to improve formatting of result)
- Create functions
-- function to convert to integer minutes (done)
-- function for performance standardizing (done)
- Compute the fastest theoretical time (done)
- Compute the median theoretical time
- Report how selected Bib Number did relative to lead (EX "989 was 0.9x at swimming, 1.1x at T1....")
- Create a line plot with each event on the X, the Standardized Time on the Y (standardize to fastest?) and each line being an athlete, highlight the user and the median line
- Need to cumsum the colums

## Future
- Use mongo db to store data
- Automatically scrape the results
- Compute a "competitiveness" score for each race (like FSAE world: https://fs-world.org/)
- Calculate the percentile for eahc event for the user

In [24]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from bokeh.plotting import figure, show
from sqlalchemy import create_engine
pd.set_option("precision", 2)

In [25]:
data = pd.read_excel('santa_cruz_data.xlsx', header = 0, index_col=None)
data.head()

We need to convert the DataTime objects contatined in the data frame to integer minutes to do all of our nice math. Use the function and create new columsn to hold the data.

Create a second set of parameters for cumulative times to use later

In [26]:
actdf = testdf[0]
type(actdf)

actdf

,Bib,Name,Team Name,City,Start Time,Swim,T1,Bike,T2,Run,Chip Elapsed,Division,Div Place,Age,Age Place,Gender,Gender Place
0,815,DOMINIC POLLIZZI,NaN,ROCKLIN,08:00:00,00:23:50,00:02:32,00:58:38,00:01:05,00:37:12,02:03:19,OLYMPIC-AGE GROUP,1,20,O/A,M,1
1,564,STEFANO PROFUMO,SANTA CRUZ TRACK CLUB,SANTA CRUZ,08:20:00,00:23:21,00:02:35,01:02:51,00:00:59,00:36:08,02:05:56,OLYMPIC-AGE GROUP,2,43,O/A,M,2
2,389,BRIAN LAVELLE,NaN,RIO DEL MAR,08:25:00,00:20:21,00:02:55,01:04:28,00:00:44,00:39:26,02:07:55,OLYMPIC-AGE GROUP,3,46,O/A,M,3
3,141,BRANTON CURT,NaN,CAMPBELL,08:10:00,00:23:37,00:04:01,01:00:03,00:01:04,00:41:49,02:10:37,OLYMPIC-AGE GROUP,4,35,1,M,4
4,644,JIMMY SOPKO,TEEM SHEEPER,MENLO PARK,08:10:00,00:24:30,00:03:16,01:03:13,00:01:33,00:38:15,02:10:49,OLYMPIC-AGE GROUP,5,39,2,M,5
5,665,JAMIE SULLIVAN,TEEM SHEEPER,MENLO PARK,08:00:00,00:23:51,00:03:52,01:09:47,00:00:54,00:34:11,02:12:38,OLYMPIC-AGE GROUP,6,26,1,M,6
6,612,YUTARO SANO,NaN,MILL VALLEY,08:10:00,00:21:38,00:03:08,01:07:34,00:01:05,00:39:47,02:13:15,OLYMPIC-AGE GROUP,7,33,1,M,7
7,182,BLAINE EGAN,HANSYM RACING,SAN FRANCISCO,08:20:00,00:24:07,00:03:33,01:04:51,00:01:36,00:39:47,02:13:54,OLYMPIC-AGE GROUP,8,40,1,M,8
8,260,ANNA GUZMAN,NaN,SAN JOSE,08:05:00,00:21:30,00:05:41,01:06:27,00:01:20,00:39:07,02:14:07,OLYMPIC-AGE GROUP,9,32,O/A,F,1
9,211,RONAN FOUCHER,KIWAMI RACING,REDWOOD CITY,08:10:00,00:26:02,00:04:02,01:03:54,00:01:16,00:40:31,02:15:48,OLYMPIC-AGE GROUP,10,39,3,M,9
10,546,NATHAN PERRY,NaN,NaN,08:00:00,00:20:07,00:03:21,01:12:00,00:00:59,00:39:30,02:16:00,OLYMPIC-AGE GROUP,11,15,1,M,10
11,723,MATTHEW WAN,NaN,WILSON,08:00:00,00:24:01,00:03:53,01:11:09,00:01:20,00:35:51,02:16:16,OLYMPIC-AGE GROUP,12,23,1,M,11
12,85,MILES CAMERON,NORTHWESTERN TRIATHLON CLUB,RENO,08:00:00,00:23:27,00:03:56,01:07:46,00:01:07,00:40:33,02:16:51,OLYMPIC-AGE GROUP,13,23,2,M,12
13,699,KEES VAN DER MEER,NaN,SANTA CRUZ,08:00:00,00:22:04,00:03:41,01:12:25,00:00:44,00:38:01,02:16:57,OLYMPIC-AGE GROUP,14,15,2,M,13
14,84,ANDY CAHOY,NaN,PORTOLA VALLY,08:10:00,00:27:10,00:02:51,01:08:49,00:00:49,00:37:20,02:17:02,OLYMPIC-AGE GROUP,15,35,4,M,14
15,494,CAMERON NAWOSAD,NaN,MOUNTAIN VIW,08:00:00,00:26:39,00:03:37,01:06:15,00:01:35,00:39:07,02:17:15,OLYMPIC-AGE GROUP,16,26,2,M,15
16,268,BRIAN HAMPTON,NaN,MOUNTAIN VIEW,08:20:00,00:25:30,00:03:51,01:06:43,00:00:56,00:40:20,02:17:22,OLYMPIC-AGE GROUP,17,41,2,M,16
17,426,GAVIN LYNCH,NaN,NaN,08:00:00,00:23:53,00:04:51,01:08:37,00:01:04,00:39:44,02:18:11,OLYMPIC-AGE GROUP,18,17,3,M,17
18,458,SVEN MAWSON,TRIFORCE,WOODSIDE,08:20:00,00:22:30,00:05:03,01:08:13,00:00:43,00:43:19,02:19:49,OLYMPIC-AGE GROUP,19,44,3,M,18
19,72,LEO BUC,NaN,UKIAH,08:10:00,00:27:37,00:03:33,01:05:06,00:00:57,00:42:53,02:20:08,OLYMPIC-AGE GROUP,20,37,5,M,19
20,509,MARK OFOSU,NaN,DAVIS,08:00:00,00:25:19,00:03:41,01:10:54,00:00:52,00:39:38,02:20:26,OLYMPIC-AGE GROUP,21,29,3,M,20
21,399,BENJAMIN YVES LELEVIER MARTINEZ,JOBY AVIATION,TEMPE,08:00:00,00:26:35,00:03:00,01:12:23,00:01:24,00:37:24,02:20:48,OLYMPIC-AGE GROUP,22,26,4,M,21
22,136,PAUL COUSINEAU,NaN,BURLINGAME,08:30:00,00:21:22,00:04:57,01:10:19,00:02:31,00:41:41,02:20:52,OLYMPIC-AGE GROUP,23,50,1,M,22
23,398,JARNO LEKKERKERKER,TEAM ZOOT,CUPERTINO,08:25:00,00:28:37,00:03:36,01:05:01,00:01:16,00:42:31,02:21:03,OLYMPIC-AGE GROUP,24,45,1,M,23
24,316,JOHN HUTCHINSON,TRI GRIT,SAN RAFAEL,08:20:00,00:25:47,00:03:02,01:08:31,00:00:49,00:42:52,02:21:03,OLYMPIC-AGE GROUP,25,43,4,M,24
25,107,MIKE CHEN,SILICON VALLEY TRIATHLON CLUB,PALO ALTO,08:10:00,00:28:30,00:03:49,01:07:44,00:00:58,00:40:17,02:21:22,OLYMPIC-AGE GROUP,26,30,2,M,25
26,344,JAMES KELLEY,NaN,BRENTWOOD,08:00:00,00:23:22,00:03:08,01:10:04,00:00:56,00:43:51,02:21:22,OLYMPIC-AGE GROUP,27,23,3,M,26
27,352,MICHAEL KIEDEL,NaN,PALOMAR PARK,08:25:00,00:19:52,00:04:28,01:08:40,00:00:46,00:47:42,02:21:29,OLYMPIC-AGE GROUP,28,46,2,M,27
28,720,ANDREY VYRVICH,GOLDEN GATE TRI CLUB,SAN FRANCISCO,08:10:00,00:26:44,00:04:32,01:07:02,00:01:05,00:42:11,02:21:36,OLYMPIC-AGE GROUP,29,37,6,M,28
29,335,SEAN JUDKINS-BOERI,GOLDEN GATE TRI CLUB,SAN FRANCISCO,08:00:00,00:25:28,00:03:55,01:09:36,00:01:16,00:41:45,02:22:01,OLYMPIC-AGE GROUP,30,29,5,M,29
30,479,CHRISTOPHER MISHIMA,GOLDEN GATE TRI CLUB,EL CERRITO,08:10:00,00:28:05,00:01:40,01:06:44,00:00:56,00:44:40,02:22:07,OLYMPIC-AGE GROUP,31,32,3,M,30
31,13,MIKE ALLEN,NaN,LIVERMORE,08:10:00,00:28:12,00:05:01,01:07:37,00:01:50,00:40:37,02:23:20,OLYMPIC-AGE GROUP,32,32,4,M,31
32,828,SARAH ANNE KIETZER,NaN,SANTA CRUZ,08:05:00,00:21:03,00:03:36,01:13:42,00:01:00,00:44:08,02:23:31,OLYMPIC-AGE GROUP,33,29,O/A,F,2
33,752,MATTHEW XUEREB,NaN,SAN CARLOS,08:00:00,00:27:29,00:03:35,01:10:24,00:01:22,00:40:50,02:23:42,OLYMPIC-AGE GROUP,34,29,6,M,32
34,350,PATRICK KENNY,GOLDEN GATE TRI CLUB,SAN FRANCISCO,08:10:00,00:28:30,00:03:40,01:10:45,00:01:32,00:39:18,02:23:47,OLYMPIC-AGE GROUP,35,31,5,M,33
35,34,TROY BARBA,HINGE HEALTH,CUPERTINO,08:25:00,00:28:02,00:04:07,01:08:36,00:01:32,00:42:02,02:24:21,OLYMPIC-AGE GROUP,36,45,3,M,34
36,823,DENNIS VANDERMEER,VAN DER MEER RACING,SANTA CRUZ,08:00:00,00:28:07,00:03:49,00:00:00,00:00:00,02:24:21,02:24:21,OLYMPIC-AGE GROUP,37,58,1,M,35
37,655,KURT STIEHL,NaN,LOS GATOS,08:10:00,00:28:14,00:03:50,01:09:05,00:01:13,00:41:59,02:24:23,OLYMPIC-AGE GROUP,38,37,7,M,36
38,453,ANDREW MASON,NaN,APTOS,08:10:00,00:25:50,00:04:59,01:08:57,00:01:38,00:43:00,02:24:26,OLYMPIC-AGE GROUP,39,38,8,M,37
39,833,TREVOR TAYLOR,KAIN PERFORMANCE,LOS GATOS,08:25:00,00:26:58,00:03:54,01:07:41,00:01:29,00:44:30,02:24:34,OLYMPIC-AGE GROUP,40,49,4,M,38
40,830,CATHERINE BREED,NaN,MILL VALLEY,08:05:00,00:19:00,00:03:05,01:13:37,00:00:52,00:48:05,02:24:40,OLYMPIC-AGE GROUP,41,28,O/A,F,3
41,562,EMIL PRAUN,NaN,UNION CITY,08:25:00,00:26:57,00:03:20,01:07:02,00:01:11,00:46:14,02:24:46,OLYMPIC-AGE GROUP,42,46,5,M,39
42,496,MEGHAN NESBIT,NaN,SACRAMENTO,08:05:00,00:24:22,00:03:19,01:14:09,00:00:56,00:42:01,02:24:50,OLYMPIC-AGE GROUP,43,26,1,F,4
43,146,LIAM DAVIS,NaN,CHICO,08:00:00,00:00:00,00:00:00,01:38:44,00:01:20,00:44:52,02:24:57,OLYMPIC-AGE GROUP,44,21,4,M,40
44,553,SIARGEY PISARCHYK,TRIFORCE CA,SUNNYVALE,08:20:00,00:28:53,00:04:26,01:11:36,00:01:03,00:39:18,02:25:17,OLYMPIC-AGE GROUP,45,41,5,M,41
45,694,SEAN UPSON,NaN,HAYWARD,08:00:00,00:26:25,00:04:58,01:13:17,00:01:24,00:39:29,02:25:35,OLYMPIC-AGE GROUP,46,28,7,M,42
46,364,BEN KORTLANG,NaN,PORTOLA VALLY,08:25:00,00:28:09,00:03:42,01:10:09,00:01:19,00:42:15,02:25:37,OLYMPIC-AGE GROUP,47,46,6,M,43
47,473,WILLIE MENDELSON,NaN,BOSTON,08:00:00,00:23:31,00:05:56,01:09:37,00:01:37,00:45:18,02:26:02,OLYMPIC-AGE GROUP,48,29,8,M,44
48,446,BARRETT MARTIN,NaN,MONTEREY,08:10:00,00:32:07,00:05:16,01:08:36,00:01:29,00:39:04,02:26:34,OLYMPIC-AGE GROUP,49,32,6,M,45
49,594,VILEN RODESKI,KAIN PERFORMANCE,SANTA CLARA,08:10:00,00:32:50,00:01:29,01:05:39,00:01:00,00:45:46,02:26:46,OLYMPIC-AGE GROUP,50,39,9,M,46

In [27]:
#create a function to convert the time to integer seconds
#To create a new column, use the [] brackets with the new column name at the left side of the assignment.

def convertTime (time):
    timeMinutes = (time.hour*60)+(time.minute)+(time.second/60)
    return timeMinutes

#convert to integers
data["Swim Minutes"] = data["Swim"].apply(convertTime)
data["T1 Minutes"] = data["T1"].apply(convertTime)
data["Bike Minutes"] = data["Bike"].apply(convertTime)
data["T2 Minutes"] = data["T2"].apply(convertTime)
data["Run Minutes"] = data["Run"].apply(convertTime)
#data["Elapsed Minutes"] = data["Chip Elapsed"].apply(convertTime)

#create cumulative times
data["Swim+T1"]=data["Swim Minutes"]+data["T1 Minutes"]
data["Plus Bike"]=data["Swim+T1"]+data["Bike Minutes"]
data["Plus T2"]=data["Plus Bike"]+data["T2 Minutes"]
data["Total"]=data["Plus T2"]+data["Run Minutes"]

Get statistical data about the event.

In [28]:
summary = data.describe()
data[["Swim Minutes", "T1 Minutes", "Bike Minutes", "T2 Minutes", "Run Minutes"]].describe()

       Swim Minutes  T1 Minutes  Bike Minutes  T2 Minutes  Run Minutes
count         26.00       26.00         26.00       26.00        26.00
mean          14.41        5.39         40.58        1.59        25.75
std            1.47        1.03          2.44        0.48         2.06
min           11.85        4.23         36.03        0.82        22.73
25%           13.52        4.62         39.20        1.29        24.12
50%           14.29        5.17         40.26        1.50        25.27
75%           15.15        5.75         41.93        1.86        27.25
max           18.30        8.07         47.55        2.97        30.08

In [29]:
#assign user variable
user = "SAMANTHA DEWEES"
index = data.index[data['Name']==user].tolist()
data.loc[index, ["Name", "Age", "Gender Place", "Swim", "T1", "Bike", "T2", "Run"]]

,Name,Age,Gender Place,Swim,T1,Bike,T2,Run
12,SAMANTHA DEWEES,25.0,13.0,00:15:02,00:07:04,00:39:39,00:02:13,00:23:38

In [30]:
def getMinTime (stage):
    minTime = data[stage].min()
    minIndex = data[stage].idxmin()
    #print("minTime is", minTime)
    #print("minIndex is", minIndex)
    return minTime, minIndex
    
def printResults (minIndex):
    #need to make this so it doesnt print reduntant colums or prints something nicely formatted
    print(data.iloc[minIndex,:])

In [31]:
events = ['Swim Minutes', 'T1 Minutes', 'Bike Minutes', 'T2 Minutes', 'Run Minutes']

shortestTime = 0
for stage in events:
    minTime, minIndex = getMinTime(stage)
    print("the fastest for ", stage)
    printResults(minIndex)
    shortestTime = shortestTime + minTime

print("the shortest possible time is: ", shortestTime)
#need to work on formatting

the fastest for  Swim Minutes
Bib                         1288
Name            CAROLE YOSHIWARA
Team Name                    NaN
City                   SUNNYVALE
Start Time              09:45:00
Swim                    00:11:51
T1                      00:05:18
Bike                    00:42:36
T2                      00:01:27
Run                     00:24:47
Chip Elapsed            01:26:02
Division        SPRINT-AGE GROUP
Div Place                   52.0
Age                         33.0
Age Place                      2
Gender                         F
Gender Place                10.0
Swim Minutes               11.85
T1 Minutes                   5.3
Bike Minutes                42.6
T2 Minutes                  1.45
Run Minutes                24.78
Swim+T1                    17.15
Plus Bike                  59.75
Plus T2                     61.2
Total                      85.98
Name: 9, dtype: object
the fastest for  T1 Minutes
Bib                                         1006
Name                                  JAMIE FEND
Team Name       SANTA CRUZ TRIATHLON ASSOCIATION
City                                       APTOS
Start Time                              09:45:00
Swim                                    00:15:14
T1                                      00:04:14
Bike                                    00:38:08
T2                                      00:01:20
Run                                     00:22:48
Chip Elapsed                            01:21:46
Division                        SPRINT-AGE GROUP
Div Place                                   32.0
Age                                         46.0
Age Place                                    O/A
Gender                                         F
Gender Place                                 2.0
Swim Minutes                               15.23
T1 Minutes                                  4.23
Bike Minutes                               38.13
T2 Minutes                                  1.33
Run Minutes                                 22.8
Swim+T1                                    19.47
Plus Bike                                   57.6
Plus T2                                    58.93
Total                                      81.73
Name: 1, dtype: object
the fastest for  Bike Minutes
Bib                         1039
Name            CHRISTINA HEPPER
Team Name                    NaN
City                 MORGAN HILL
Start Time              09:45:00
Swim                    00:14:00
T1                      00:04:15
Bike                    00:36:02
T2                      00:01:20
Run                     00:23:40
Chip Elapsed            01:19:20
Division        SPRINT-AGE GROUP
Div Place                   25.0
Age                         53.0
Age Place                    O/A
Gender                         F
Gender Place                 1.0
Swim Minutes                14.0
T1 Minutes                  4.25
Bike Minutes               36.03
T2 Minutes                  1.33
Run Minutes                23.67
Swim+T1                    18.25
Plus Bike                  54.28
Plus T2                    55.62
Total                      79.28
Name: 0, dtype: object
the fastest for  T2 Minutes
Bib                          946
Name               DENISE BUTLER
Team Name                    NaN
City               MOUNTAIN VIEW
Start Time              09:45:00
Swim                    00:12:34
T1                      00:04:37
Bike                    00:40:08
T2                      00:00:49
Run                     00:24:46
Chip Elapsed            01:22:56
Division        SPRINT-AGE GROUP
Div Place                   39.0
Age                         34.0
Age Place                      1
Gender                         F
Gender Place                 5.0
Swim Minutes               12.57
T1 Minutes                  4.62
Bike Minutes               40.13
T2 Minutes                  0.82
Run Minutes                24.77
Swim+T1                    17.18
Plus Bike                  57.32
Plus T2                    58.13
Total                       82.9
Name: 4, dtype: object
the fastest for  Run Minutes
Bib                         1112
Name              ALEXANDRA LUZI
Team Name                    NaN
City               SAN FRANCISCO
Start Time              09:45:00
Swim                    00:12:50
T1                      00:06:41
Bike                    00:38:04
T2                      00:01:48
Run                     00:22:44
Chip Elapsed            01:22:08
Division        SPRINT-AGE GROUP
Div Place                   35.0
Age                         30.0
Age Place                    O/A
Gender                         F
Gender Place                 3.0
Swim Minutes               12.83
T1 Minutes                  6.68
Bike Minutes               38.07
T2 Minutes                   1.8
Run Minutes                22.73
Swim+T1                    19.52
Plus Bike                  57.58
Plus T2                    59.38
Total                      82.12
Name: 2, dtype: object
the shortest possible time is:  75.66666666666666

In [32]:
reduced2 = data[["Name","Swim Minutes","Swim+T1","Plus Bike","Plus T2","Total","Gender Place"]]
reduced2["Start"] = 0
reduced2 = reduced2.drop(25)
reduced2

# color_nums = reduced2['Gender Place'].tolist()
# color_names = reduced2['Name'].tolist()
# colors_zip = zip(color_nums, color_names)

# colors_zip

<ipython-input-32-16d8c57e1e0f>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Name,Swim Minutes,Swim+T1,Plus Bike,Plus T2,Total,Gender Place,Start
0,CHRISTINA HEPPER,14.00,18.25,54.28,55.62,79.28,1.0,0
1,JAMIE FEND,15.23,19.47,57.60,58.93,81.73,2.0,0
2,ALEXANDRA LUZI,12.83,19.52,57.58,59.38,82.12,3.0,0
3,SUMI HACHMANN,14.27,18.93,57.53,58.72,82.65,4.0,0
4,DENISE BUTLER,12.57,17.18,57.32,58.13,82.90,5.0,0
5,SHARON BARCLAY,14.52,18.95,55.17,56.55,83.22,6.0,0
6,AMY PEARSON,13.50,17.98,56.98,58.67,83.47,7.0,0
7,NOEL KOSIEK,13.57,17.92,56.97,58.18,85.33,8.0,0
8,CATHERINE LONDON,14.13,19.78,59.65,62.62,85.88,9.0,0
9,CAROLE YOSHIWARA,11.85,17.15,59.75,61.20,85.98,10.0,0
10,JACKI PHELPS,13.82,18.88,60.13,62.10,87.47,11.0,0
11,HELENA SCUTT,14.48,20.27,60.65,62.85,87.53,12.0,0
12,SAMANTHA DEWEES,15.03,22.10,61.75,63.97,87.60,13.0,0
13,CARA HIPSKIND,12.93,17.18,59.07,60.68,87.75,14.0,0
14,AYA TANGE,14.32,19.95,59.70,61.58,87.78,15.0,0
15,CHRISTA ZADO,18.30,23.15,62.83,64.35,89.52,16.0,0
16,KERRY SKEMP,16.50,22.10,64.80,65.78,90.58,17.0,0
17,VYLANA TRANG,13.03,19.37,62.97,64.87,90.65,18.0,0
18,CHRIS ENGEN,14.47,19.78,60.20,61.70,91.00,19.0,0
19,EMILY SHEPARD,13.90,21.97,61.68,63.97,91.68,20.0,0
20,MARISA LENCI,15.18,20.30,63.17,64.45,91.73,21.0,0
21,MARIE CHAISSON,15.83,21.05,62.35,64.05,92.22,22.0,0
22,HANNAH VOELKER,12.65,19.92,67.47,68.77,92.30,23.0,0
23,KATHERINE LEE,16.62,21.27,63.22,64.72,93.13,24.0,0
24,TINA SOMERS,14.88,21.20,64.32,65.40,93.18,25.0,0

In [33]:
dimensions = list([
            dict(range = [0, 1],
                label = 'Start', values = reduced2['Start']),            
            dict(range = [reduced2["Swim Minutes"].min(), reduced2["Swim Minutes"].max()],
                label = 'Time After Swim', values = reduced2['Swim Minutes']),
            dict(range = [reduced2["Swim+T1"].min(), reduced2["Swim+T1"].max()],
                label = 'Time After First Transition', values = reduced2['Swim+T1']),
            dict(range = [reduced2["Plus Bike"].min(), reduced2["Plus Bike"].max()],
                label = 'Time After Bike', values = reduced2['Plus Bike']),
            dict(range = [reduced2["Plus T2"].min(), reduced2["Plus T2"].max()],
                label = 'Time After Second Transition', values = reduced2['Plus T2']),
            dict(range = [reduced2["Total"].min(), reduced2["Total"].max()],
                label = 'Total Time', values = reduced2['Total']),
            dict(range=[0,reduced2['Gender Place'].max()], tickvals = reduced2['Gender Place'], ticktext = reduced2['Name'],
                       label='Competitor', values=reduced2['Gender Place'])
        ])

fig = go.Figure(data=go.Parcoords(line = dict(color = reduced2['Gender Place'],
                   colorscale = [[.0,'rgba(255,0,0,0.1)'],[0.2,'rgba(0,255,0,0.1)'],[.4,'rgba(0,0,255,0.1)'], 
                                 [.6,'rgba(0,255,255,0.1)'], [.8, 'rgba(255,0,255,0.1)'], [1, 'rgba(0,0,0,0.1)']]), dimensions=dimensions))

fig.update_layout(
    title="Triathalon Results",
    width=1920,
    height=1080
)

fig.show()

In [15]:
engine = create_engine('sqlite:///data.db', echo=False)

In [16]:
sql_df = pd.read_sql('data.db', con=engine, index_col='ID')

In [17]:
sql_df.head()

,Bib,Name,Team Name,City,Start Time,Swim,T1,Bike,T2,Run,Chip Elapsed,Division,Div Place,Age,Age Place,Gender,Gender Place
ID,,,,,,,,,,,,,,,,,
0,1051,MANUEL HUECKEL,TEAM WY55,SAN FRANCISCO,09:35:00,00:10:11,00:03:08,00:31:19,00:00:44,00:19:10,01:04:34,SPRINT-AGE GROUP,1,23,O/A,M,1
1,978,TYLER CURRAN,,WHITE PLAINS,09:35:00,00:09:28,00:02:59,00:31:42,00:00:52,00:20:14,01:05:16,SPRINT-AGE GROUP,2,24,O/A,M,2
2,924,BRIAN BERGER,GOLD COUNTRY TRIATHLON CLUB,LINCOLN,09:35:00,00:09:33,00:03:53,00:33:12,00:01:25,00:22:02,01:10:08,SPRINT-AGE GROUP,3,25,O/A,M,3
3,1187,CLAY ROBBINS,,REDWOOD CITY,09:35:00,00:11:30,00:03:42,00:34:03,00:01:37,00:19:26,01:10:19,SPRINT-AGE GROUP,4,30,1,M,4
4,943,ANDREW BUNNER,,BELMONT,09:40:00,00:11:46,00:03:49,00:33:34,00:01:06,00:20:54,01:11:12,SPRINT-AGE GROUP,5,44,1,M,5

In [35]:
import dash
from dash import dcc
from dash import html

In [37]:
app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig)
])

In [38]:
app.run_server(debug=True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on